[build-system]
requires = ["setuptools>=72"]
build-backend = "setuptools.build_meta"

[project]
name = "azarrot"
description = "An OpenAI compatible server, focusing on OpenVINO usage."
license = {file = "LICENSE"}
authors = [
  {name = "notsyncing", email = "song.fc@gmail.com"},
]
readme = "README.md"
requires-python = "<= 3.12.99, >=3.12"
version = "0.4.0"
dependencies = [
    "openvino==2025.4.0",
    "optimum[openvino]==2.0.0",
    "optimum-intel==1.26.1",
    "transformers==4.55.4",
    "sentence-transformers==5.1.2",
    "torch==2.9.0+xpu",
    "torchvision",
    "torchaudio",
    "accelerate==1.12.0",
    "gptqmodel[ipex]==4.2.5",
    "autoawq==0.2.9",
    "uvicorn==0.38.0",
    "fastapi==0.124.0",
    "pyyaml==6.0.3",
    "jinja2==3.1.6",
    "python-multipart==0.0.20",
    "huggingface_hub==0.34.4",
    "SQLAlchemy==2.0.41",
    "sqlakeyset==2.0.1746777265",
    "alembic==1.17.2",
    "schedule==1.2.2",
    "pycron==3.2.0",
    "pymilvus==2.6.2",
    "langchain==0.3.27",
    "langchain-community==0.3.29",
    "langchain-milvus==0.2.1",
    "langchain-unstructured[local]==0.1.6",
    "dataclass-wizard==0.35.1",
    "psutil==7.1.3",
    "decord==0.6.0",
    "einops==0.8.1",
    "timm==1.0.22",

    # These are gptqmodel dependencies
    "logbar",
    "tokenicer",
    "device-smi",
]
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 3 - Alpha",

  # Indicate who your project is intended for
  "Intended Audience :: End Users/Desktop",
  "Topic :: Internet",

  # Pick your license as you wish (see also "license" above)
  "License :: OSI Approved :: Apache Software License",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
dev = [
    "tox",
    "azarrot[lint]",
    "azarrot[test]",
    "azarrot[doc]",
    "azarrot[build]",
    "types-PyYAML==6.0.12.20250516"
]
lint = [
    "mypy",
    "ruff",
]
test = [
    "pytest==9.0.2",
    "pytest-cov==7.0.0",
    "expecttest==0.3.0",
    "coverage[toml]==7.13.0",
    "openai==2.9.0",
    "cohere==5.20.0",
]
doc = [
    "sphinx",
    "myst-parser",
    "furo",
]
build = [
    "build[virtualenv]==1.3.0",
]

[tool.uv]
override-dependencies = []
index-strategy = "unsafe-best-match"
no-build-isolation-package = ["gptqmodel"]
prerelease = "allow"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/xpu"

[project.scripts]
azarrot = "azarrot.server:main"

[tool.ruff]
line-length = 120
src = ["src"]
extend-exclude = [
    "conf.py",
]
target-version = "py312"
lint.select = ["ALL"]
lint.ignore = [
    "BLE001",
    "C901",
    "D100",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D200",
    "D415",
    "EM101",
    "EM102",
    "E712",
    "E722",
    "ERA001",
    "COM812",   # Conflicts with the formatter
    "ISC001",   # Conflicts with the formatter
    "ANN401",
    "PT001",    # https://github.com/astral-sh/ruff/issues/8796#issuecomment-1825907715
    "PT023",    # https://github.com/astral-sh/ruff/issues/8796#issuecomment-1825907715
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "DTZ005",
    "DTZ006",
    "DTZ901",
    "TRY003",
    "TRY004",
    "FBT001",
    "FBT002",
    "RET505",
    "SIM102",
    "N812",
    "S101",
    "TD002",
    "TD003",
    "FIX002",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "S101", # Use of `assert` detected
    "RUF001",
    "PLR2004",
    "SLF001",
]
"**/__init__.py" = [
    "D104",
    "F401", # Imported but unused
    "F403", # Wildcard imports
]
"docs/**" = [
    "INP001",   # Requires __init__.py but docs folder is not a package.
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`(https://github.com/astral-sh/ruff/issues/5434)
keep-runtime-typing = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
disallow_untyped_defs = true # Functions need to be annotated
warn_unused_ignores = true
ignore_missing_imports = true
exclude = [
    "azarrot-\\d+", # Ignore temporary folder created by setuptools when building an sdist
    "venv/",
    "venv.*/",
    "build/",
    "dist/",
    "docs/",
    "models/",
    "tests/"
]

[tool.pytest.ini_options]
addopts = """
    --import-mode=append
    --cov=azarrot
    --cov-config=pyproject.toml
    --cov-report=
    """
log_cli = true
log_cli_level = "INFO"

[tool.coverage.paths]
# Maps coverage measured in site-packages to source files in src
source = ["src/", ".tox/*/lib/python*/site-packages/"]

[tool.coverage.html]
directory = "reports/coverage_html"
